# Generated by Django 3.2.7 on 2021-11-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customers',
            new_name='customer',
        ),
    ]
