# Generated by Django 3.2.7 on 2021-11-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_customers_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customers',
            new_name='customer',
        ),
    ]
